name: itwillrock_neumorphism
description: Neumorphic controls and controls environment implementation.
version: 0.1.16
homepage: https://github.com/coredeveloper/itwillrock_ui/tree/main/neumorphism/itwillrock_mobile_ui
repository: https://github.com/coredeveloper/itwillrock_ui/tree/main/neumorphism/itwillrock_mobile_ui
screenshots:
  - description: 'Light theme demo of the example controls'
    path: demo.gif
  - description: 'Dark theme demo of the example controls'
    path: demo_dark.gif

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1
flutter:
